// Copyright (c) 2012 DotNetAnywhere
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

#if NO

typedef float  (STDCALL *_fC)();
typedef double (STDCALL *_dC)();
typedef ulong    (STDCALL *_uC)();
typedef float  (STDCALL *_fCf)(float _0);
typedef float  (STDCALL *_fCd)(double _0);
typedef float  (STDCALL *_fCu)(uint _0);
typedef double (STDCALL *_dCf)(float _0);
typedef double (STDCALL *_dCd)(double _0);
typedef double (STDCALL *_dCu)(uint _0);
typedef ulong    (STDCALL *_uCf)(float _0);
typedef ulong    (STDCALL *_uCd)(double _0);
typedef ulong    (STDCALL *_uCu)(uint _0);
typedef float  (STDCALL *_fCff)(float _0, float _1);
typedef float  (STDCALL *_fCfd)(float _0, double _1);
typedef float  (STDCALL *_fCfu)(float _0, uint _1);
typedef float  (STDCALL *_fCdf)(double _0, float _1);
typedef float  (STDCALL *_fCdd)(double _0, double _1);
typedef float  (STDCALL *_fCdu)(double _0, uint _1);
typedef float  (STDCALL *_fCuf)(uint _0, float _1);
typedef float  (STDCALL *_fCud)(uint _0, double _1);
typedef float  (STDCALL *_fCuu)(uint _0, uint _1);
typedef double (STDCALL *_dCff)(float _0, float _1);
typedef double (STDCALL *_dCfd)(float _0, double _1);
typedef double (STDCALL *_dCfu)(float _0, uint _1);
typedef double (STDCALL *_dCdf)(double _0, float _1);
typedef double (STDCALL *_dCdd)(double _0, double _1);
typedef double (STDCALL *_dCdu)(double _0, uint _1);
typedef double (STDCALL *_dCuf)(uint _0, float _1);
typedef double (STDCALL *_dCud)(uint _0, double _1);
typedef double (STDCALL *_dCuu)(uint _0, uint _1);
typedef ulong    (STDCALL *_uCff)(float _0, float _1);
typedef ulong    (STDCALL *_uCfd)(float _0, double _1);
typedef ulong    (STDCALL *_uCfu)(float _0, uint _1);
typedef ulong    (STDCALL *_uCdf)(double _0, float _1);
typedef ulong    (STDCALL *_uCdd)(double _0, double _1);
typedef ulong    (STDCALL *_uCdu)(double _0, uint _1);
typedef ulong    (STDCALL *_uCuf)(uint _0, float _1);
typedef ulong    (STDCALL *_uCud)(uint _0, double _1);
typedef ulong    (STDCALL *_uCuu)(uint _0, uint _1);
typedef float  (STDCALL *_fCfff)(float _0, float _1, float _2);
typedef float  (STDCALL *_fCffd)(float _0, float _1, double _2);
typedef float  (STDCALL *_fCffu)(float _0, float _1, uint _2);
typedef float  (STDCALL *_fCfdf)(float _0, double _1, float _2);
typedef float  (STDCALL *_fCfdd)(float _0, double _1, double _2);
typedef float  (STDCALL *_fCfdu)(float _0, double _1, uint _2);
typedef float  (STDCALL *_fCfuf)(float _0, uint _1, float _2);
typedef float  (STDCALL *_fCfud)(float _0, uint _1, double _2);
typedef float  (STDCALL *_fCfuu)(float _0, uint _1, uint _2);
typedef float  (STDCALL *_fCdff)(double _0, float _1, float _2);
typedef float  (STDCALL *_fCdfd)(double _0, float _1, double _2);
typedef float  (STDCALL *_fCdfu)(double _0, float _1, uint _2);
typedef float  (STDCALL *_fCddf)(double _0, double _1, float _2);
typedef float  (STDCALL *_fCddd)(double _0, double _1, double _2);
typedef float  (STDCALL *_fCddu)(double _0, double _1, uint _2);
typedef float  (STDCALL *_fCduf)(double _0, uint _1, float _2);
typedef float  (STDCALL *_fCdud)(double _0, uint _1, double _2);
typedef float  (STDCALL *_fCduu)(double _0, uint _1, uint _2);
typedef float  (STDCALL *_fCuff)(uint _0, float _1, float _2);
typedef float  (STDCALL *_fCufd)(uint _0, float _1, double _2);
typedef float  (STDCALL *_fCufu)(uint _0, float _1, uint _2);
typedef float  (STDCALL *_fCudf)(uint _0, double _1, float _2);
typedef float  (STDCALL *_fCudd)(uint _0, double _1, double _2);
typedef float  (STDCALL *_fCudu)(uint _0, double _1, uint _2);
typedef float  (STDCALL *_fCuuf)(uint _0, uint _1, float _2);
typedef float  (STDCALL *_fCuud)(uint _0, uint _1, double _2);
typedef float  (STDCALL *_fCuuu)(uint _0, uint _1, uint _2);
typedef double (STDCALL *_dCfff)(float _0, float _1, float _2);
typedef double (STDCALL *_dCffd)(float _0, float _1, double _2);
typedef double (STDCALL *_dCffu)(float _0, float _1, uint _2);
typedef double (STDCALL *_dCfdf)(float _0, double _1, float _2);
typedef double (STDCALL *_dCfdd)(float _0, double _1, double _2);
typedef double (STDCALL *_dCfdu)(float _0, double _1, uint _2);
typedef double (STDCALL *_dCfuf)(float _0, uint _1, float _2);
typedef double (STDCALL *_dCfud)(float _0, uint _1, double _2);
typedef double (STDCALL *_dCfuu)(float _0, uint _1, uint _2);
typedef double (STDCALL *_dCdff)(double _0, float _1, float _2);
typedef double (STDCALL *_dCdfd)(double _0, float _1, double _2);
typedef double (STDCALL *_dCdfu)(double _0, float _1, uint _2);
typedef double (STDCALL *_dCddf)(double _0, double _1, float _2);
typedef double (STDCALL *_dCddd)(double _0, double _1, double _2);
typedef double (STDCALL *_dCddu)(double _0, double _1, uint _2);
typedef double (STDCALL *_dCduf)(double _0, uint _1, float _2);
typedef double (STDCALL *_dCdud)(double _0, uint _1, double _2);
typedef double (STDCALL *_dCduu)(double _0, uint _1, uint _2);
typedef double (STDCALL *_dCuff)(uint _0, float _1, float _2);
typedef double (STDCALL *_dCufd)(uint _0, float _1, double _2);
typedef double (STDCALL *_dCufu)(uint _0, float _1, uint _2);
typedef double (STDCALL *_dCudf)(uint _0, double _1, float _2);
typedef double (STDCALL *_dCudd)(uint _0, double _1, double _2);
typedef double (STDCALL *_dCudu)(uint _0, double _1, uint _2);
typedef double (STDCALL *_dCuuf)(uint _0, uint _1, float _2);
typedef double (STDCALL *_dCuud)(uint _0, uint _1, double _2);
typedef double (STDCALL *_dCuuu)(uint _0, uint _1, uint _2);
typedef ulong    (STDCALL *_uCfff)(float _0, float _1, float _2);
typedef ulong    (STDCALL *_uCffd)(float _0, float _1, double _2);
typedef ulong    (STDCALL *_uCffu)(float _0, float _1, uint _2);
typedef ulong    (STDCALL *_uCfdf)(float _0, double _1, float _2);
typedef ulong    (STDCALL *_uCfdd)(float _0, double _1, double _2);
typedef ulong    (STDCALL *_uCfdu)(float _0, double _1, uint _2);
typedef ulong    (STDCALL *_uCfuf)(float _0, uint _1, float _2);
typedef ulong    (STDCALL *_uCfud)(float _0, uint _1, double _2);
typedef ulong    (STDCALL *_uCfuu)(float _0, uint _1, uint _2);
typedef ulong    (STDCALL *_uCdff)(double _0, float _1, float _2);
typedef ulong    (STDCALL *_uCdfd)(double _0, float _1, double _2);
typedef ulong    (STDCALL *_uCdfu)(double _0, float _1, uint _2);
typedef ulong    (STDCALL *_uCddf)(double _0, double _1, float _2);
typedef ulong    (STDCALL *_uCddd)(double _0, double _1, double _2);
typedef ulong    (STDCALL *_uCddu)(double _0, double _1, uint _2);
typedef ulong    (STDCALL *_uCduf)(double _0, uint _1, float _2);
typedef ulong    (STDCALL *_uCdud)(double _0, uint _1, double _2);
typedef ulong    (STDCALL *_uCduu)(double _0, uint _1, uint _2);
typedef ulong    (STDCALL *_uCuff)(uint _0, float _1, float _2);
typedef ulong    (STDCALL *_uCufd)(uint _0, float _1, double _2);
typedef ulong    (STDCALL *_uCufu)(uint _0, float _1, uint _2);
typedef ulong    (STDCALL *_uCudf)(uint _0, double _1, float _2);
typedef ulong    (STDCALL *_uCudd)(uint _0, double _1, double _2);
typedef ulong    (STDCALL *_uCudu)(uint _0, double _1, uint _2);
typedef ulong    (STDCALL *_uCuuf)(uint _0, uint _1, float _2);
typedef ulong    (STDCALL *_uCuud)(uint _0, uint _1, double _2);
typedef ulong    (STDCALL *_uCuuu)(uint _0, uint _1, uint _2);
typedef float  (STDCALL *_fCffff)(float _0, float _1, float _2, float _3);
typedef float  (STDCALL *_fCfffd)(float _0, float _1, float _2, double _3);
typedef float  (STDCALL *_fCfffu)(float _0, float _1, float _2, uint _3);
typedef float  (STDCALL *_fCffdf)(float _0, float _1, double _2, float _3);
typedef float  (STDCALL *_fCffdd)(float _0, float _1, double _2, double _3);
typedef float  (STDCALL *_fCffdu)(float _0, float _1, double _2, uint _3);
typedef float  (STDCALL *_fCffuf)(float _0, float _1, uint _2, float _3);
typedef float  (STDCALL *_fCffud)(float _0, float _1, uint _2, double _3);
typedef float  (STDCALL *_fCffuu)(float _0, float _1, uint _2, uint _3);
typedef float  (STDCALL *_fCfdff)(float _0, double _1, float _2, float _3);
typedef float  (STDCALL *_fCfdfd)(float _0, double _1, float _2, double _3);
typedef float  (STDCALL *_fCfdfu)(float _0, double _1, float _2, uint _3);
typedef float  (STDCALL *_fCfddf)(float _0, double _1, double _2, float _3);
typedef float  (STDCALL *_fCfddd)(float _0, double _1, double _2, double _3);
typedef float  (STDCALL *_fCfddu)(float _0, double _1, double _2, uint _3);
typedef float  (STDCALL *_fCfduf)(float _0, double _1, uint _2, float _3);
typedef float  (STDCALL *_fCfdud)(float _0, double _1, uint _2, double _3);
typedef float  (STDCALL *_fCfduu)(float _0, double _1, uint _2, uint _3);
typedef float  (STDCALL *_fCfuff)(float _0, uint _1, float _2, float _3);
typedef float  (STDCALL *_fCfufd)(float _0, uint _1, float _2, double _3);
typedef float  (STDCALL *_fCfufu)(float _0, uint _1, float _2, uint _3);
typedef float  (STDCALL *_fCfudf)(float _0, uint _1, double _2, float _3);
typedef float  (STDCALL *_fCfudd)(float _0, uint _1, double _2, double _3);
typedef float  (STDCALL *_fCfudu)(float _0, uint _1, double _2, uint _3);
typedef float  (STDCALL *_fCfuuf)(float _0, uint _1, uint _2, float _3);
typedef float  (STDCALL *_fCfuud)(float _0, uint _1, uint _2, double _3);
typedef float  (STDCALL *_fCfuuu)(float _0, uint _1, uint _2, uint _3);
typedef float  (STDCALL *_fCdfff)(double _0, float _1, float _2, float _3);
typedef float  (STDCALL *_fCdffd)(double _0, float _1, float _2, double _3);
typedef float  (STDCALL *_fCdffu)(double _0, float _1, float _2, uint _3);
typedef float  (STDCALL *_fCdfdf)(double _0, float _1, double _2, float _3);
typedef float  (STDCALL *_fCdfdd)(double _0, float _1, double _2, double _3);
typedef float  (STDCALL *_fCdfdu)(double _0, float _1, double _2, uint _3);
typedef float  (STDCALL *_fCdfuf)(double _0, float _1, uint _2, float _3);
typedef float  (STDCALL *_fCdfud)(double _0, float _1, uint _2, double _3);
typedef float  (STDCALL *_fCdfuu)(double _0, float _1, uint _2, uint _3);
typedef float  (STDCALL *_fCddff)(double _0, double _1, float _2, float _3);
typedef float  (STDCALL *_fCddfd)(double _0, double _1, float _2, double _3);
typedef float  (STDCALL *_fCddfu)(double _0, double _1, float _2, uint _3);
typedef float  (STDCALL *_fCdddf)(double _0, double _1, double _2, float _3);
typedef float  (STDCALL *_fCdddd)(double _0, double _1, double _2, double _3);
typedef float  (STDCALL *_fCdddu)(double _0, double _1, double _2, uint _3);
typedef float  (STDCALL *_fCdduf)(double _0, double _1, uint _2, float _3);
typedef float  (STDCALL *_fCddud)(double _0, double _1, uint _2, double _3);
typedef float  (STDCALL *_fCdduu)(double _0, double _1, uint _2, uint _3);
typedef float  (STDCALL *_fCduff)(double _0, uint _1, float _2, float _3);
typedef float  (STDCALL *_fCdufd)(double _0, uint _1, float _2, double _3);
typedef float  (STDCALL *_fCdufu)(double _0, uint _1, float _2, uint _3);
typedef float  (STDCALL *_fCdudf)(double _0, uint _1, double _2, float _3);
typedef float  (STDCALL *_fCdudd)(double _0, uint _1, double _2, double _3);
typedef float  (STDCALL *_fCdudu)(double _0, uint _1, double _2, uint _3);
typedef float  (STDCALL *_fCduuf)(double _0, uint _1, uint _2, float _3);
typedef float  (STDCALL *_fCduud)(double _0, uint _1, uint _2, double _3);
typedef float  (STDCALL *_fCduuu)(double _0, uint _1, uint _2, uint _3);
typedef float  (STDCALL *_fCufff)(uint _0, float _1, float _2, float _3);
typedef float  (STDCALL *_fCuffd)(uint _0, float _1, float _2, double _3);
typedef float  (STDCALL *_fCuffu)(uint _0, float _1, float _2, uint _3);
typedef float  (STDCALL *_fCufdf)(uint _0, float _1, double _2, float _3);
typedef float  (STDCALL *_fCufdd)(uint _0, float _1, double _2, double _3);
typedef float  (STDCALL *_fCufdu)(uint _0, float _1, double _2, uint _3);
typedef float  (STDCALL *_fCufuf)(uint _0, float _1, uint _2, float _3);
typedef float  (STDCALL *_fCufud)(uint _0, float _1, uint _2, double _3);
typedef float  (STDCALL *_fCufuu)(uint _0, float _1, uint _2, uint _3);
typedef float  (STDCALL *_fCudff)(uint _0, double _1, float _2, float _3);
typedef float  (STDCALL *_fCudfd)(uint _0, double _1, float _2, double _3);
typedef float  (STDCALL *_fCudfu)(uint _0, double _1, float _2, uint _3);
typedef float  (STDCALL *_fCuddf)(uint _0, double _1, double _2, float _3);
typedef float  (STDCALL *_fCuddd)(uint _0, double _1, double _2, double _3);
typedef float  (STDCALL *_fCuddu)(uint _0, double _1, double _2, uint _3);
typedef float  (STDCALL *_fCuduf)(uint _0, double _1, uint _2, float _3);
typedef float  (STDCALL *_fCudud)(uint _0, double _1, uint _2, double _3);
typedef float  (STDCALL *_fCuduu)(uint _0, double _1, uint _2, uint _3);
typedef float  (STDCALL *_fCuuff)(uint _0, uint _1, float _2, float _3);
typedef float  (STDCALL *_fCuufd)(uint _0, uint _1, float _2, double _3);
typedef float  (STDCALL *_fCuufu)(uint _0, uint _1, float _2, uint _3);
typedef float  (STDCALL *_fCuudf)(uint _0, uint _1, double _2, float _3);
typedef float  (STDCALL *_fCuudd)(uint _0, uint _1, double _2, double _3);
typedef float  (STDCALL *_fCuudu)(uint _0, uint _1, double _2, uint _3);
typedef float  (STDCALL *_fCuuuf)(uint _0, uint _1, uint _2, float _3);
typedef float  (STDCALL *_fCuuud)(uint _0, uint _1, uint _2, double _3);
typedef float  (STDCALL *_fCuuuu)(uint _0, uint _1, uint _2, uint _3);
typedef double (STDCALL *_dCffff)(float _0, float _1, float _2, float _3);
typedef double (STDCALL *_dCfffd)(float _0, float _1, float _2, double _3);
typedef double (STDCALL *_dCfffu)(float _0, float _1, float _2, uint _3);
typedef double (STDCALL *_dCffdf)(float _0, float _1, double _2, float _3);
typedef double (STDCALL *_dCffdd)(float _0, float _1, double _2, double _3);
typedef double (STDCALL *_dCffdu)(float _0, float _1, double _2, uint _3);
typedef double (STDCALL *_dCffuf)(float _0, float _1, uint _2, float _3);
typedef double (STDCALL *_dCffud)(float _0, float _1, uint _2, double _3);
typedef double (STDCALL *_dCffuu)(float _0, float _1, uint _2, uint _3);
typedef double (STDCALL *_dCfdff)(float _0, double _1, float _2, float _3);
typedef double (STDCALL *_dCfdfd)(float _0, double _1, float _2, double _3);
typedef double (STDCALL *_dCfdfu)(float _0, double _1, float _2, uint _3);
typedef double (STDCALL *_dCfddf)(float _0, double _1, double _2, float _3);
typedef double (STDCALL *_dCfddd)(float _0, double _1, double _2, double _3);
typedef double (STDCALL *_dCfddu)(float _0, double _1, double _2, uint _3);
typedef double (STDCALL *_dCfduf)(float _0, double _1, uint _2, float _3);
typedef double (STDCALL *_dCfdud)(float _0, double _1, uint _2, double _3);
typedef double (STDCALL *_dCfduu)(float _0, double _1, uint _2, uint _3);
typedef double (STDCALL *_dCfuff)(float _0, uint _1, float _2, float _3);
typedef double (STDCALL *_dCfufd)(float _0, uint _1, float _2, double _3);
typedef double (STDCALL *_dCfufu)(float _0, uint _1, float _2, uint _3);
typedef double (STDCALL *_dCfudf)(float _0, uint _1, double _2, float _3);
typedef double (STDCALL *_dCfudd)(float _0, uint _1, double _2, double _3);
typedef double (STDCALL *_dCfudu)(float _0, uint _1, double _2, uint _3);
typedef double (STDCALL *_dCfuuf)(float _0, uint _1, uint _2, float _3);
typedef double (STDCALL *_dCfuud)(float _0, uint _1, uint _2, double _3);
typedef double (STDCALL *_dCfuuu)(float _0, uint _1, uint _2, uint _3);
typedef double (STDCALL *_dCdfff)(double _0, float _1, float _2, float _3);
typedef double (STDCALL *_dCdffd)(double _0, float _1, float _2, double _3);
typedef double (STDCALL *_dCdffu)(double _0, float _1, float _2, uint _3);
typedef double (STDCALL *_dCdfdf)(double _0, float _1, double _2, float _3);
typedef double (STDCALL *_dCdfdd)(double _0, float _1, double _2, double _3);
typedef double (STDCALL *_dCdfdu)(double _0, float _1, double _2, uint _3);
typedef double (STDCALL *_dCdfuf)(double _0, float _1, uint _2, float _3);
typedef double (STDCALL *_dCdfud)(double _0, float _1, uint _2, double _3);
typedef double (STDCALL *_dCdfuu)(double _0, float _1, uint _2, uint _3);
typedef double (STDCALL *_dCddff)(double _0, double _1, float _2, float _3);
typedef double (STDCALL *_dCddfd)(double _0, double _1, float _2, double _3);
typedef double (STDCALL *_dCddfu)(double _0, double _1, float _2, uint _3);
typedef double (STDCALL *_dCdddf)(double _0, double _1, double _2, float _3);
typedef double (STDCALL *_dCdddd)(double _0, double _1, double _2, double _3);
typedef double (STDCALL *_dCdddu)(double _0, double _1, double _2, uint _3);
typedef double (STDCALL *_dCdduf)(double _0, double _1, uint _2, float _3);
typedef double (STDCALL *_dCddud)(double _0, double _1, uint _2, double _3);
typedef double (STDCALL *_dCdduu)(double _0, double _1, uint _2, uint _3);
typedef double (STDCALL *_dCduff)(double _0, uint _1, float _2, float _3);
typedef double (STDCALL *_dCdufd)(double _0, uint _1, float _2, double _3);
typedef double (STDCALL *_dCdufu)(double _0, uint _1, float _2, uint _3);
typedef double (STDCALL *_dCdudf)(double _0, uint _1, double _2, float _3);
typedef double (STDCALL *_dCdudd)(double _0, uint _1, double _2, double _3);
typedef double (STDCALL *_dCdudu)(double _0, uint _1, double _2, uint _3);
typedef double (STDCALL *_dCduuf)(double _0, uint _1, uint _2, float _3);
typedef double (STDCALL *_dCduud)(double _0, uint _1, uint _2, double _3);
typedef double (STDCALL *_dCduuu)(double _0, uint _1, uint _2, uint _3);
typedef double (STDCALL *_dCufff)(uint _0, float _1, float _2, float _3);
typedef double (STDCALL *_dCuffd)(uint _0, float _1, float _2, double _3);
typedef double (STDCALL *_dCuffu)(uint _0, float _1, float _2, uint _3);
typedef double (STDCALL *_dCufdf)(uint _0, float _1, double _2, float _3);
typedef double (STDCALL *_dCufdd)(uint _0, float _1, double _2, double _3);
typedef double (STDCALL *_dCufdu)(uint _0, float _1, double _2, uint _3);
typedef double (STDCALL *_dCufuf)(uint _0, float _1, uint _2, float _3);
typedef double (STDCALL *_dCufud)(uint _0, float _1, uint _2, double _3);
typedef double (STDCALL *_dCufuu)(uint _0, float _1, uint _2, uint _3);
typedef double (STDCALL *_dCudff)(uint _0, double _1, float _2, float _3);
typedef double (STDCALL *_dCudfd)(uint _0, double _1, float _2, double _3);
typedef double (STDCALL *_dCudfu)(uint _0, double _1, float _2, uint _3);
typedef double (STDCALL *_dCuddf)(uint _0, double _1, double _2, float _3);
typedef double (STDCALL *_dCuddd)(uint _0, double _1, double _2, double _3);
typedef double (STDCALL *_dCuddu)(uint _0, double _1, double _2, uint _3);
typedef double (STDCALL *_dCuduf)(uint _0, double _1, uint _2, float _3);
typedef double (STDCALL *_dCudud)(uint _0, double _1, uint _2, double _3);
typedef double (STDCALL *_dCuduu)(uint _0, double _1, uint _2, uint _3);
typedef double (STDCALL *_dCuuff)(uint _0, uint _1, float _2, float _3);
typedef double (STDCALL *_dCuufd)(uint _0, uint _1, float _2, double _3);
typedef double (STDCALL *_dCuufu)(uint _0, uint _1, float _2, uint _3);
typedef double (STDCALL *_dCuudf)(uint _0, uint _1, double _2, float _3);
typedef double (STDCALL *_dCuudd)(uint _0, uint _1, double _2, double _3);
typedef double (STDCALL *_dCuudu)(uint _0, uint _1, double _2, uint _3);
typedef double (STDCALL *_dCuuuf)(uint _0, uint _1, uint _2, float _3);
typedef double (STDCALL *_dCuuud)(uint _0, uint _1, uint _2, double _3);
typedef double (STDCALL *_dCuuuu)(uint _0, uint _1, uint _2, uint _3);
typedef ulong    (STDCALL *_uCffff)(float _0, float _1, float _2, float _3);
typedef ulong    (STDCALL *_uCfffd)(float _0, float _1, float _2, double _3);
typedef ulong    (STDCALL *_uCfffu)(float _0, float _1, float _2, uint _3);
typedef ulong    (STDCALL *_uCffdf)(float _0, float _1, double _2, float _3);
typedef ulong    (STDCALL *_uCffdd)(float _0, float _1, double _2, double _3);
typedef ulong    (STDCALL *_uCffdu)(float _0, float _1, double _2, uint _3);
typedef ulong    (STDCALL *_uCffuf)(float _0, float _1, uint _2, float _3);
typedef ulong    (STDCALL *_uCffud)(float _0, float _1, uint _2, double _3);
typedef ulong    (STDCALL *_uCffuu)(float _0, float _1, uint _2, uint _3);
typedef ulong    (STDCALL *_uCfdff)(float _0, double _1, float _2, float _3);
typedef ulong    (STDCALL *_uCfdfd)(float _0, double _1, float _2, double _3);
typedef ulong    (STDCALL *_uCfdfu)(float _0, double _1, float _2, uint _3);
typedef ulong    (STDCALL *_uCfddf)(float _0, double _1, double _2, float _3);
typedef ulong    (STDCALL *_uCfddd)(float _0, double _1, double _2, double _3);
typedef ulong    (STDCALL *_uCfddu)(float _0, double _1, double _2, uint _3);
typedef ulong    (STDCALL *_uCfduf)(float _0, double _1, uint _2, float _3);
typedef ulong    (STDCALL *_uCfdud)(float _0, double _1, uint _2, double _3);
typedef ulong    (STDCALL *_uCfduu)(float _0, double _1, uint _2, uint _3);
typedef ulong    (STDCALL *_uCfuff)(float _0, uint _1, float _2, float _3);
typedef ulong    (STDCALL *_uCfufd)(float _0, uint _1, float _2, double _3);
typedef ulong    (STDCALL *_uCfufu)(float _0, uint _1, float _2, uint _3);
typedef ulong    (STDCALL *_uCfudf)(float _0, uint _1, double _2, float _3);
typedef ulong    (STDCALL *_uCfudd)(float _0, uint _1, double _2, double _3);
typedef ulong    (STDCALL *_uCfudu)(float _0, uint _1, double _2, uint _3);
typedef ulong    (STDCALL *_uCfuuf)(float _0, uint _1, uint _2, float _3);
typedef ulong    (STDCALL *_uCfuud)(float _0, uint _1, uint _2, double _3);
typedef ulong    (STDCALL *_uCfuuu)(float _0, uint _1, uint _2, uint _3);
typedef ulong    (STDCALL *_uCdfff)(double _0, float _1, float _2, float _3);
typedef ulong    (STDCALL *_uCdffd)(double _0, float _1, float _2, double _3);
typedef ulong    (STDCALL *_uCdffu)(double _0, float _1, float _2, uint _3);
typedef ulong    (STDCALL *_uCdfdf)(double _0, float _1, double _2, float _3);
typedef ulong    (STDCALL *_uCdfdd)(double _0, float _1, double _2, double _3);
typedef ulong    (STDCALL *_uCdfdu)(double _0, float _1, double _2, uint _3);
typedef ulong    (STDCALL *_uCdfuf)(double _0, float _1, uint _2, float _3);
typedef ulong    (STDCALL *_uCdfud)(double _0, float _1, uint _2, double _3);
typedef ulong    (STDCALL *_uCdfuu)(double _0, float _1, uint _2, uint _3);
typedef ulong    (STDCALL *_uCddff)(double _0, double _1, float _2, float _3);
typedef ulong    (STDCALL *_uCddfd)(double _0, double _1, float _2, double _3);
typedef ulong    (STDCALL *_uCddfu)(double _0, double _1, float _2, uint _3);
typedef ulong    (STDCALL *_uCdddf)(double _0, double _1, double _2, float _3);
typedef ulong    (STDCALL *_uCdddd)(double _0, double _1, double _2, double _3);
typedef ulong    (STDCALL *_uCdddu)(double _0, double _1, double _2, uint _3);
typedef ulong    (STDCALL *_uCdduf)(double _0, double _1, uint _2, float _3);
typedef ulong    (STDCALL *_uCddud)(double _0, double _1, uint _2, double _3);
typedef ulong    (STDCALL *_uCdduu)(double _0, double _1, uint _2, uint _3);
typedef ulong    (STDCALL *_uCduff)(double _0, uint _1, float _2, float _3);
typedef ulong    (STDCALL *_uCdufd)(double _0, uint _1, float _2, double _3);
typedef ulong    (STDCALL *_uCdufu)(double _0, uint _1, float _2, uint _3);
typedef ulong    (STDCALL *_uCdudf)(double _0, uint _1, double _2, float _3);
typedef ulong    (STDCALL *_uCdudd)(double _0, uint _1, double _2, double _3);
typedef ulong    (STDCALL *_uCdudu)(double _0, uint _1, double _2, uint _3);
typedef ulong    (STDCALL *_uCduuf)(double _0, uint _1, uint _2, float _3);
typedef ulong    (STDCALL *_uCduud)(double _0, uint _1, uint _2, double _3);
typedef ulong    (STDCALL *_uCduuu)(double _0, uint _1, uint _2, uint _3);
typedef ulong    (STDCALL *_uCufff)(uint _0, float _1, float _2, float _3);
typedef ulong    (STDCALL *_uCuffd)(uint _0, float _1, float _2, double _3);
typedef ulong    (STDCALL *_uCuffu)(uint _0, float _1, float _2, uint _3);
typedef ulong    (STDCALL *_uCufdf)(uint _0, float _1, double _2, float _3);
typedef ulong    (STDCALL *_uCufdd)(uint _0, float _1, double _2, double _3);
typedef ulong    (STDCALL *_uCufdu)(uint _0, float _1, double _2, uint _3);
typedef ulong    (STDCALL *_uCufuf)(uint _0, float _1, uint _2, float _3);
typedef ulong    (STDCALL *_uCufud)(uint _0, float _1, uint _2, double _3);
typedef ulong    (STDCALL *_uCufuu)(uint _0, float _1, uint _2, uint _3);
typedef ulong    (STDCALL *_uCudff)(uint _0, double _1, float _2, float _3);
typedef ulong    (STDCALL *_uCudfd)(uint _0, double _1, float _2, double _3);
typedef ulong    (STDCALL *_uCudfu)(uint _0, double _1, float _2, uint _3);
typedef ulong    (STDCALL *_uCuddf)(uint _0, double _1, double _2, float _3);
typedef ulong    (STDCALL *_uCuddd)(uint _0, double _1, double _2, double _3);
typedef ulong    (STDCALL *_uCuddu)(uint _0, double _1, double _2, uint _3);
typedef ulong    (STDCALL *_uCuduf)(uint _0, double _1, uint _2, float _3);
typedef ulong    (STDCALL *_uCudud)(uint _0, double _1, uint _2, double _3);
typedef ulong    (STDCALL *_uCuduu)(uint _0, double _1, uint _2, uint _3);
typedef ulong    (STDCALL *_uCuuff)(uint _0, uint _1, float _2, float _3);
typedef ulong    (STDCALL *_uCuufd)(uint _0, uint _1, float _2, double _3);
typedef ulong    (STDCALL *_uCuufu)(uint _0, uint _1, float _2, uint _3);
typedef ulong    (STDCALL *_uCuudf)(uint _0, uint _1, double _2, float _3);
typedef ulong    (STDCALL *_uCuudd)(uint _0, uint _1, double _2, double _3);
typedef ulong    (STDCALL *_uCuudu)(uint _0, uint _1, double _2, uint _3);
typedef ulong    (STDCALL *_uCuuuf)(uint _0, uint _1, uint _2, float _3);
typedef ulong    (STDCALL *_uCuuud)(uint _0, uint _1, uint _2, double _3);
typedef ulong    (STDCALL *_uCuuuu)(uint _0, uint _1, uint _2, uint _3);

#endif
